#!/bin/sh

set -o errexit
set -o nounset

worker_ready() {
    celery -A band_saas inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

flower \
    --app=band_saas \
    --broker="${CELERY_BROKER}"