version: '3.7'

services:

  redis:
    image: redis:5-alpine

  django:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: /start
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"

  celery:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: /start-celeryworker
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

  flower:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command:  /start-flower
    ports:
      - 5555:5555
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env

