version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    command: /start
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
