version: '3.7'

services:

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    env_file:
      - .env

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"

