# Generated by Django 3.1.7 on 2021-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discogs', '0002_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
    ]
