# Generated by Django 3.1.7 on 2021-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogs", "0003_release_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
