# Generated by Django 3.1.7 on 2021-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogs", "0004_auto_20210227_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="image",
            field=models.ImageField(blank=True, upload_to="discography_images/"),
        ),
        migrations.AddField(
            model_name="release",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
