# Generated by Django 3.1.7 on 2021-05-03 12:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discogs', '0005_auto_20210503_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
