# Generated by Django 3.1.7 on 2021-10-10 22:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogs", "0006_auto_20210503_1238"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_info", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
