# Generated by Django 3.1.7 on 2021-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogs", "0009_auto_20211221_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="label",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
